msgfmt zh_book.g.po -o ../mo/zh_CN/LC_MESSAGES/book.mo
msgfmt zh_calculator.g.po -o ../mo/zh_CN/LC_MESSAGES/calculator.mo
msgfmt zh_menu.g.po -o ../mo/zh_CN/LC_MESSAGES/menu.mo
msgfmt zh_help.g.po -o ../mo/zh_CN/LC_MESSAGES/help.mo
msgfmt zh_music.g.po -o ../mo/zh_CN/LC_MESSAGES/music.mo
msgfmt zh_recorder.g.po -o ../mo/zh_CN/LC_MESSAGES/recorder.mo
msgfmt zh_radio.g.po -o ../mo/zh_CN/LC_MESSAGES/radio.mo
msgfmt zh_desktop.g.po -o ../mo/zh_CN/LC_MESSAGES/desktop.mo
msgfmt zh_file-management.g.po -o ../mo/zh_CN/LC_MESSAGES/file-management.mo
msgfmt zh_backup.g.po -o ../mo/zh_CN/LC_MESSAGES/backup.mo
msgfmt zh_format.g.po -o ../mo/zh_CN/LC_MESSAGES/format.mo
msgfmt zh_pc-connector.g.po -o ../mo/zh_CN/LC_MESSAGES/pc-connector.mo
msgfmt zh_update_plextalk.g.po -o ../mo/zh_CN/LC_MESSAGES/update_plextalk.mo
msgfmt zh_libinfo.g.po -o ../mo/zh_CN/LC_MESSAGES/libinfo.mo
msgfmt zh_jump-page.g.po -o ../mo/zh_CN/LC_MESSAGES/jump-page.mo

msgfmt tw_book.g.po -o ../mo/zh_TW/LC_MESSAGES/book.mo
msgfmt tw_calculator.g.po -o ../mo/zh_TW/LC_MESSAGES/calculator.mo
msgfmt tw_menu.g.po -o ../mo/zh_TW/LC_MESSAGES/menu.mo
msgfmt tw_help.g.po -o ../mo/zh_TW/LC_MESSAGES/help.mo
msgfmt tw_music.g.po -o ../mo/zh_TW/LC_MESSAGES/music.mo
msgfmt tw_recorder.g.po -o ../mo/zh_TW/LC_MESSAGES/recorder.mo
msgfmt tw_radio.g.po -o ../mo/zh_TW/LC_MESSAGES/radio.mo
msgfmt tw_desktop.g.po -o ../mo/zh_TW/LC_MESSAGES/desktop.mo
msgfmt tw_file-management.g.po -o ../mo/zh_TW/LC_MESSAGES/file-management.mo
msgfmt tw_backup.g.po -o ../mo/zh_TW/LC_MESSAGES/backup.mo
msgfmt tw_format.g.po -o ../mo/zh_TW/LC_MESSAGES/format.mo
msgfmt tw_pc-connector.g.po -o ../mo/zh_TW/LC_MESSAGES/pc-connector.mo
msgfmt tw_update_plextalk.g.po -o ../mo/zh_TW/LC_MESSAGES/update_plextalk.mo
msgfmt tw_libinfo.g.po -o ../mo/zh_TW/LC_MESSAGES/libinfo.mo
msgfmt tw_jump-page.g.po -o ../mo/zh_TW/LC_MESSAGES/jump-page.mo

msgfmt id_book.g.po -o ../mo/hi_IN/LC_MESSAGES/book.mo
msgfmt id_calculator.g.po -o ../mo/hi_IN/LC_MESSAGES/calculator.mo
msgfmt id_menu.g.po -o ../mo/hi_IN/LC_MESSAGES/menu.mo
msgfmt id_help.g.po -o ../mo/hi_IN/LC_MESSAGES/help.mo
msgfmt id_music.g.po -o ../mo/hi_IN/LC_MESSAGES/music.mo
msgfmt id_recorder.g.po -o ../mo/hi_IN/LC_MESSAGES/recorder.mo
msgfmt id_radio.g.po -o ../mo/hi_IN/LC_MESSAGES/radio.mo
msgfmt id_desktop.g.po -o ../mo/hi_IN/LC_MESSAGES/desktop.mo
msgfmt id_file-management.g.po -o ../mo/hi_IN/LC_MESSAGES/file-management.mo
msgfmt id_backup.g.po -o ../mo/hi_IN/LC_MESSAGES/backup.mo
msgfmt id_format.g.po -o ../mo/hi_IN/LC_MESSAGES/format.mo
msgfmt id_pc-connector.g.po -o ../mo/hi_IN/LC_MESSAGES/pc-connector.mo
msgfmt id_update_plextalk.g.po -o ../mo/hi_IN/LC_MESSAGES/update_plextalk.mo
msgfmt id_libinfo.g.po -o ../mo/hi_IN/LC_MESSAGES/libinfo.mo
msgfmt id_jump-page.g.po -o ../mo/hi_IN/LC_MESSAGES/jump-page.mo
